from .health import router as health_router
from .lab import router as lab_router
from .hitl import router as hitl_router
from .dashboard import router as dashboard_router
from .ws import router as ws_router
from .rag import router as rag_router
from .ti import router as ti_router
from .toolkit import router as toolkit_router
from .data_sources import router as data_sources_router
from .chat import router as chat_router
