"""Front matter: title page, approval sheet, abstracts, TOC, lists, nomenclature."""
from helpers import (add_para, add_heading, add_table, add_field,
                     add_page_break)


def build():
    # ── Title page ──
    add_para("Awarded by", align="center", size=14)
    add_para("AgeixAISOC", align="center", bold=True, size=18)
    add_para("An AI-Orchestrated Cyber Defense Platform", align="center", bold=True, size=16)
    add_para("A thesis submitted by", align="center", size=16)
    for name in ["Aziz Ragab Aziz", "Emad Hassan", "Mohamed Hany", "Taha Alghonaimi"]:
        add_para(name, align="center", bold=True, size=16)
    add_para("A dissertation submitted in partial fulfillment of the requirements "
             "for the degree of", align="center", size=12)
    add_para("Digilians 9 Months Diploma in Applied Cybersecurity Track",
             align="center", bold=True, size=12)
    add_para("Under supervision of", align="center", bold=True, size=16)
    add_para("General supervisor", align="center", size=14)
    add_para("Dr. Rabab M. Nabawy", align="center", bold=True, size=14)
    add_para("Academic Director", align="center", size=14)
    add_para("Dr. Ahmed Tobal", align="center", bold=True, size=14)
    add_para("August 2026", align="center", size=12)
    add_page_break()

    # ── Approval sheet ──
    add_para("Approval Sheet", align="center", bold=True, size=16)
    add_para("Thesis Title: AgeixAISOC — An AI-Orchestrated Cyber Defense Platform",
             align="center", size=12)
    add_para("A thesis submitted by", align="center", size=12)
    add_para("Aziz Ragab Aziz, Emad Hassan, Mohamed Hany, Taha Alghonaimi",
             align="center", size=12)
    add_para("A dissertation submitted in partial fulfillment of the requirements "
             "for the degree of", align="center", size=12)
    add_para("Digilians 9 Months Diploma — Cybersecurity Track",
             align="center", bold=True, size=12)
    add_para("Approved by the examination committee", align="center", size=12)
    add_table(["Name", "Signature"],
              [["Prof.", ""], ["Prof.", ""], ["Prof.", ""], ["", ""]])
    add_page_break()

    # ── Abstract (English) ──
    add_heading("Abstract", 1)
    for p in [
        "Security Operations Centers (SOCs) increasingly struggle to keep pace with growing alert volume, analyst shortages, and adversaries that adapt faster than static detection rules. Industry data shows that a typical SOC handles more than ten thousand alerts per day, of which roughly seventy percent are false positives, while the mean time to detect a breach in some organizations still exceeds two hundred days. This combination of noise and latency is the central problem this thesis addresses.",
        "This project presents AgeixAISOC, an AI-orchestrated Security Operations Center platform designed around one governing principle: artificial intelligence detects, correlates, scores, and recommends, while a human analyst retains final authority over any consequential action. The platform is built around a LangGraph-based master orchestrator that coordinates a set of specialized agents responsible for threat detection, risk scoring, threat hunting, recommendation generation, forensics, red-team validation, blue-team coverage checking, user and entity behavior analytics (UEBA), and open-source intelligence (OSINT) enrichment. These agents operate on top of a live Wazuh SIEM integration used for telemetry ingestion and Sigma rule deployment.",
        "A Human-in-the-Loop (HITL) approval workflow governs every high-impact response action before it reaches execution, and every decision, whether generated by an agent or made by a human analyst, is captured in an auditable trail. A Retrieval-Augmented Generation (RAG) memory layer over ChromaDB enables the platform to learn from analyst feedback, automatically suppressing or de-prioritizing repeat false positives. This design choice directly targets the accountability and trust gaps identified in fully autonomous security-response systems.",
        "The system was developed and validated inside an isolated lab network comprising a FortiGate firewall, a Wazuh SIEM manager and agent pair, an Active Directory domain controller, and both vulnerable and attacker hosts. This lab-first approach allowed the detection and orchestration logic to be exercised against realistic, repeatable attack scenarios without any risk to production infrastructure.",
        "This document describes the problem motivating the work, the target and as-built architecture, the methodology used to design and validate the platform, the results achieved to date — reported honestly at the subsystem level — and the roadmap of future work required to mature AgeixAISOC from a working prototype into a governance-ready platform.",
    ]:
        add_para(p)
    add_para("Keywords: SOC, AI Orchestration, Human-in-the-Loop, SIEM, SOAR, "
             "Multi-Agent Systems, LangGraph, CrewAI, Wazuh, Sigma Rules, "
             "MITRE ATT&CK, Retrieval-Augmented Generation.", italic=True)
    add_page_break()

    # ── Abstract (Arabic) ──
    add_heading("ملخص المشروع (Arabic Abstract)", 1)
    for p in [
        "تواجه مراكز العمليات الأمنية (SOCs) تحديات متزايدة في مواكبة الحجم الهائل من التنبيهات الأمنية، ونقص المحللين المؤهلين، وخصوم يتطورون بسرعة تفوق قدرة قواعد الكشف الثابتة على التكيف. تشير بيانات الصناعة إلى أن مركز العمليات الأمنية النموذجي يتعامل مع أكثر من عشرة آلاف تنبيه يومياً، منها نحو سبعين بالمائة إنذارات كاذبة، بينما لا يزال متوسط زمن اكتشاف الاختراق في بعض المؤسسات يتجاوز مائتي يوم.",
        "يقدم هذا المشروع منصة AgeixAISOC، وهي منصة عمليات أمنية منسقة بالذكاء الاصطناعي، مبنية على مبدأ أساسي: يقوم الذكاء الاصطناعي بالكشف والربط والتقييم والتوصية، بينما يحتفظ المحلل البشري بالسلطة النهائية على أي إجراء ذي تأثير فعلي. تعتمد المنصة على عقل منسق رئيسي مبني على إطار LangGraph، ينسق مجموعة من الوكلاء المتخصصين المسؤولين عن اكتشاف التهديدات، وتقييم المخاطر، وصيد التهديدات، وتوليد التوصيات، والتحقق من الفريق الأحمر والأزرق، وتحليل سلوك المستخدمين، وجمع المعلومات الاستخباراتية مفتوحة المصدر، وذلك بالتكامل المباشر مع نظام Wazuh SIEM لاستقبال البيانات ونشر قواعد Sigma.",
        "يضمن سير عمل الموافقة البشرية (Human-in-the-Loop) عدم تنفيذ أي إجراء عالي التأثير دون موافقة صريحة من المحلل، ويتم تسجيل كل قرار — سواء صادر عن الوكيل الذكي أو عن الإنسان — في سجل تدقيق كامل قابل للمراجعة. كما تتيح طبقة الذاكرة المعززة بالاسترجاع (RAG) المبنية على ChromaDB للمنصة التعلم من ملاحظات المحللين، وقمع أو تخفيض أولوية الإنذارات الكاذبة المتكررة تلقائياً. تم تطوير النظام والتحقق منه داخل شبكة معملية معزولة تضم جدار حماية FortiGate، ونظام Wazuh SIEM، ووحدة تحكم Active Directory، وأجهزة مستهدفة ومهاجمة.",
        "يوثق هذا المستند المشكلة الدافعة للعمل، والمعمارية المستهدفة والمنفذة فعلياً، والمنهجية المتبعة، والنتائج المحققة حتى تاريخه بأمانة على مستوى كل نظام فرعي، وخريطة طريق العمل المستقبلي اللازمة لتطوير المنصة من نموذج أولي عامل إلى منصة جاهزة للحوكمة الكاملة.",
    ]:
        add_para(p, align="right")
    add_page_break()

    # ── Acknowledgments ──
    add_heading("Acknowledgments", 1)
    for p in [
        "We would like to express our sincere gratitude to our General Supervisor, Dr. Rabab M. Nabawy, for her continuous guidance, feedback, and support throughout the course of this graduation project. Her insistence on rigor and honest reporting shaped the way this thesis presents both the achievements and the current limitations of the platform.",
        "We are equally grateful to our Project Supervisor, Eng. Abdelrazek Ali, for his hands-on technical guidance throughout the design and implementation of the lab environment and the agent pipeline, and to our Academic Director, Dr. Ahmed Tobal, for his oversight of the diploma program.",
        "We extend our thanks to the Digilians 9-Month Diploma program and the National Telecommunication Institute (NTI) for providing the training, mentorship, infrastructure, and resources that made this work possible, and to the Ministry of Communications and Information Technology for supporting the Digilians initiative.",
        "Finally, we thank our families and colleagues for their patience, encouragement, and understanding throughout the many late nights of lab testing, debugging, and writing that went into this project.",
    ]:
        add_para(p)
    add_page_break()

    # ── Table of Contents (automatic field) ──
    add_heading("Table of Contents", 1)
    add_field("Right-click and select 'Update Field' to generate the Table of Contents.",
              'TOC \\o "1-3" \\h \\z \\u')
    add_page_break()

    # ── List of Figures (automatic field) ──
    add_heading("List of Figures", 1)
    add_field("Update field to generate List of Figures.", 'TOC \\h \\z \\c "Figure"')
    add_page_break()

    # ── List of Tables (automatic field) ──
    add_heading("List of Tables", 1)
    add_field("Update field to generate List of Tables.", 'TOC \\h \\z \\c "Table"')
    add_page_break()

    # ── Nomenclature ──
    add_heading("Nomenclature", 1)
    add_table(["Abbreviation", "Meaning"], [
        ["SOC", "Security Operations Center"],
        ["SIEM", "Security Information and Event Management"],
        ["SOAR", "Security Orchestration, Automation, and Response"],
        ["HITL", "Human-in-the-Loop"],
        ["CTI", "Cyber Threat Intelligence"],
        ["EDR / NDR", "Endpoint / Network Detection and Response"],
        ["IOC", "Indicator of Compromise"],
        ["MITRE ATT&CK", "Adversarial Tactics, Techniques, and Common Knowledge"],
        ["RAG", "Retrieval-Augmented Generation"],
        ["LLM", "Large Language Model"],
        ["MTTD / MTTR", "Mean Time To Detect / Mean Time To Respond"],
        ["Sigma", "Generic, vendor-agnostic SIEM detection-rule format"],
        ["RBAC", "Role-Based Access Control"],
        ["XDR", "Extended Detection and Response"],
        ["TTP", "Tactics, Techniques, and Procedures"],
        ["UEBA", "User and Entity Behavior Analytics"],
        ["OSINT", "Open Source Intelligence"],
        ["KB", "Knowledge Base"],
    ])
    add_page_break()