"""RAG knowledge base registry and document loader."""

import logging
from typing import Any

logger = logging.getLogger(__name__)

KNOWLEDGE_BASES = {
    "past_incidents": {"name": "Past Incidents", "description": "Historical incident reports (populated from completed pipeline runs)", "doc_count": 0},
    "threat_intel": {"name": "Threat Intel", "description": "Threat actor profiles and TTPs (live Feodo Tracker feed)", "doc_count": 0},
    "sigma_rules": {"name": "Sigma Rules", "description": "SIEM detection rules (auto-generated by gap loop)", "doc_count": 0},
    "cve_kev": {"name": "CVE / KEV", "description": "Known exploited vulnerabilities", "doc_count": 0},
    "learned_decisions": {"name": "HITL Decisions", "description": "Human analyst decisions", "doc_count": 0},
    "mitre_attack": {"name": "MITRE ATT&CK", "description": "Techniques from official MITRE STIX bundle (real data, cached)", "doc_count": 0},
    "cve_data": {"name": "CVE Database", "description": "On-demand NVD API lookups for alert CVEs (real, cached)", "doc_count": 0},
}


def get_kb_names() -> list:
    return list(KNOWLEDGE_BASES.keys())


def get_kb_metadata(name: str) -> dict:
    return KNOWLEDGE_BASES.get(name, {})


def list_knowledge_bases() -> list:
    return [{"id": k, **v} for k, v in KNOWLEDGE_BASES.items()]